name: maav
description: Melrose Alliance Against Violence

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  url_launcher: ^5.1.2
  path_provider: ^1.2.0
  dio: ^2.1.13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/estate.jpg
   - assets/buttons.jpg
   - assets/logo_maav.gif
 